services:
  - type: web
    name: fastlane-redirect
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BREAKFAST_URL
        sync: false
      - key: LUNCH_URL
        sync: false
